name: Test voicevox-client

on:
  push:
    branches:
      - main
  pull_request:
    
jobs:
  tests:
    name: Test voicevox-client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install depend
        run: pip3 install -U .[tests]
      - name: Run voicevox-engine
        run: |
          docker pull voicevox/voicevox_engine:cpu-ubuntu20.04-latest
          docker run -d --rm -p '127.0.0.1:50021:50021' voicevox/voicevox_engine:cpu-ubuntu20.04-latest
          sleep 20
      - name: Run test
        run: pytest
